#change to test travis

language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: ron-burgundy # see README
  api_key:
    secure: DCI0IDe3ExYT4wBv/kmRnA/1oVO77jJ//ymvZztw9lmVPN0bHiPjGyWIRiTikF7nFjK4aQJ4TBFlD19EeAEjC6wXc2+X4qsL4cRq/CcW0szpHv+naFiTLkrEObzy/FEZx7DCF7JiMvjbSZCnGx8o5Qfqxy8PHep4U1aWxmh9lFMwlNEPhCd9eij0TeTVJWxD83wNXKNVMrfbYIlVgrM5pn+25MUSgu0TrjE/Egl2xJ4bIYMWcYUbiY/zb6LZT0Kuph2y5l4xfDAVlwg9TGPnoW6xYlQwygwcvuSAztcsTgvn3tRPjdbqArsq7Dh2NJtt8YQJuXprbbPL45LhBLK/UOMPTvRshwJtu2Yg3sVfzAnFwVV9aLNEHECQBBuEVXOIs3ccbV21GPEMTSeLYq0/5HJw9u9adArJjWnaOMUtXjWn73cmEG0o4KtSJoXMNdrULHoh6pSAsZz1X4bcrzvMLX8l/nW2ws3rtBzuBxNaiJDjpSKpQTPtwf0buUqY4Hv0y+zAJj5xgqs4qdJPBuar+9B+ncgpgna0eeRDAAjTkc/il8LpHtzWcE/E0TrhEc+83Cy0mEksuCKRmgeILqdqrKUe/+jOtfX2cGJnR//lxj2lXlNHNNKnzfz3ABeTMHt+B5gKN3f9wWIbdhDPCiT14NU2Mb+oGQD3++fyeISLnTY=
